# Generated by Django 4.2 on 2024-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_completed_remove_task_user_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
