# Generated by Django 5.1.2 on 2024-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_pointtransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointtransaction",
            name="points_used",
        ),
    ]
