# Generated by Django 4.2 on 2024-10-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_completed_tasks_count_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed_tasks_count',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
