# Generated by Django 4.2 on 2024-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_completed_tasks_count_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_tasks_count',
            field=models.IntegerField(default=0),
        ),
    ]
