# Generated by Django 4.2 on 2024-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_tasks_count',
            field=models.IntegerField(default=0),
        ),
    ]
